dataset: "FVOICE"

path:
  corpus_path: "" #corpus path (text)
  lexicon_path: "" #Not neccesary for spanish
  raw_path: "" #audios .wav 
  preprocessed_path: "C:\\Users\\derec\\OneDrive\\Documents\\F-VOICE\\preprocessed_data\\LJSpeech" #processed audios,text,textgrid and spectograms

preprocessing:
  val_size: 200   # validation set size (it has to be between 5% or 10% of sataset)
  text:
    text_cleaners: ["spanish_cleaners"]
    language: "es"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level' is better phoneme-level 
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
